title: Marek Łańduch
email: landuch@gmail.com
description: >-
  C# enthusiast
baseurl: ""
url: "https://mareklanduch.github.io"
github_username: mareklanduch

author:
  name: "Marek Łańduch"
  bio: "C# enthusiast"
  email: "landuch@gmail.com"
  github: "mareklanduch"
  linkedin: "landuch"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "sunrise"

plugins:
  - jekyll-feed
  - jekyll-include-cache